spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/siriuspro?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: siriuspro
    password: siriuspro
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
mybatis-plus:
  global-config:
    db-config:
      id-type : auto