spring:
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB

mybatis-plus:
  global-config:
    db-config:
      id-type : auto
logging:
  config: classpath:logback-spring.xml
