spring:
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
mybatis-plus:
  global-config:
    db-config:
      id-type : auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml
server:
  port: 8090

